import "../globals.css";
import { Inter } from "next/font/google";
import Navigationbar from "./_components/Navbar/navigationbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main style={{ flexDirection: "column" }}>
          <Navigationbar />
          {children}
        </main>
      </body>
    </html>
  );
}
